defaults:
  - override hydra/job_logging: default

data:
  dataset_dir: dataset
  output_dir: classification_dataset
  train_path: classification_dataset/train
  val_path: classification_dataset/valid
  test_path: classification_dataset/test

model:
  epochs: 25
  batch_size: 32
  img_size: 640
  learning_rate: 0.001
  name: resnet50

yolov5:
  data_yaml: data.yaml
  epochs: 80
  batch_size: 4
  img_size: 320

results:
  dir: 'result_transfer_learning'

hydra:
  job:
    config:
      override_dirname:
        exclude_keys:
          - model.log_progress_steps
  run:
    dir: ./result_transfer_learning/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: results/${data.path}/
    subdir: ${hydra.job.override_dirname}
  help:
    template:
      "This is the script for training GlyphNet reimplemented in PyTorch"