# config_atcnet.yaml
model:
  name: "ATCNet"
  num_classes: 171
  seed: 261
  batch_size: 8
  epochs: 10
  log_progress_steps: 1000
  learning_rate: 0.001

train:
  batch_size: 32
  learning_rate: 0.001
  num_epochs: 25

data:
  train_path: 'balanced_data/train/'
  val_path: 'balanced_data/train/'
  test_path: 'balanced_data/test/'
  val_fraction: 0.3

data_transforms:
  train:
    _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.Grayscale
        num_output_channels: 1
      - _target_: torchvision.transforms.ToTensor
  val:
    _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.Grayscale
        num_output_channels: 1
      - _target_: torchvision.transforms.ToTensor

results:
  dir: 'result_atcnet'

hydra:
  job:
    config:
      override_dirname:
        exclude_keys:
          - model.log_progress_steps
  run:
    dir: ./result_atcnet/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: results/${data.path}/
    subdir: ${hydra.job.override_dirname}
