data:
  train_path: '../datasets/classification_dataset/train/'
  val_path: '../datasets/classification_dataset/valid/'

  val_fraction: 0.3
  test_path: "../datasets/classification_dataset/test/"

train:
  batch_size: 64
  learning_rate: 0.01
  num_epochs: 10
  dropout: 0.1

results:
  dir: 'result_ensamble_learning'

model:
  seed: 42



hydra:
  job:
    config:
      override_dirname:
        exclude_keys:
          - model.log_progress_steps
  run:
    dir: ../results/result_ensamble_learning/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ../results/result_ensamble_learning/${data.path}/
    subdir: ${hydra.job.override_dirname}
  help:
    template:
      "This is the script for training GlyphNet reimplemented in PyTorch"